### ISSUE TITLE
Article for the 'Hello World' magazine

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/codeforlife-deploy-appengine#153]
## Description
'Hello World' is a free magazine from the Raspberry Pi foundation that is sent to Teachers who subscribe. It is also paid for non-teachers.

We can produce an article to show teachers how great Rapid Router is, increasing knowledge of the game and teaching resources.

## Acceptance criteria
- [ ] Include teacher testimonials
- [ ] Highlight the comprehensive teaching resources and how it fits in with the curriculum
- [ ] Tell everyone it's free, and how

**Comment by rdcruzCFL** [comment]
I have sent a draft outline to Hello World today. It is going to take me more than four days, if they accept the idea because I have suggested it as part of a series and there's bound to be much to-ing and fro-ing. 

The basic idea is why it is important to use a spiral curriculum to teach programming. After an introduction, this is the outline:
So, what is the problem for pupils – be the aged ten or aged 50 and why does a spiral approach help?
* What is the problem for pupils?
   - Way of thinking
   - Persistence
   - Curiosity	
   - Resilience
   - It’s important to get it wrong
* What is the problem for teachers?
   - Knowledge
   - Experience
   - Assessment
* Why use a spiral approach?
   - Research
* What approach do I take?
   - Year 7 – block-based programming using Rapid Router and then programming the micro:bits
   - Year 8 – flowcharting using Flowol, more Rapid Router
   - Year 9 – LMC, flowcharting using Raptor, Python supported by a self-authored Codio course and HackerRank self-marked exercises

* Explore each of these years in turn, explaining how each unit is taught and how the tools support it. 
* Comments from pupils – anonymised.

**Comment by rdcruzCFL** [comment]
I have not had any response to my email. I will get in touch with them again.
